dist: focal

# this is only required to install MATLAB such that we
# have access to HSL on the machine
language: matlab

python: 3.7 # is this actually used when language: matlab is in place?

git:
    submodules: false

before_install: 
    - git submodule update --init
    - sudo apt-get -y install python3-pip
    - sudo apt-get -y install python3-setuptools

install:
    - python3 -m pip install -e .
    - export LD_LIBRARY_PATH=$(pwd)/external/qpOASES/bin
    - export LD_LIBRARY_PATH=$(pwd)/external/casadi/installation/lib
    - matlab -batch "setenv('MATLAB_ROOT_PATH',matlabroot)"
    - pushd test
    - python3 install_dependencies.py -$MATLAB_ROOT_PATH 

script:
    - python3 test.py
