dist: focal

# this is only required to install MATLAB such that we
# have access to HSL on the machine
language: matlab

python: 3.7 # is this actually used when language: matlab is in place?

git:
    submodules: false

before_install: 
    - git submodule update --init
    - sudo apt-get -y install python3-pip
    - sudo apt-get -y install python3-setuptools
    - sudo apt-get install libgfortran5

install:
    - python3 -m pip install -e .
    - export LD_LIBRARY_PATH=$(pwd)/external/qpOASES/bin:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH=$(pwd)/external/casadi/installation/lib:$LD_LIBRARY_PATH
    - pushd test
    - matlab -batch "fileID = fopen('matlab_root_path.txt','w'); fprintf(fileID,'%s', matlabroot); fclose(fileID);"
    - python3 install_dependencies.py 'matlab_root_path.txt' 
    - export LD_LIBRARY_PATH=$(<matlab_root_path.txt)/bin/glnxa64:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH=$(pwd)/fsqp_solver:$LD_LIBRARY_PATH
    - echo $LD_LIBRARY_PATH
    - pwd
    - ls
    - python3 test.py
